### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by RubenCordeiro** [zaccolley/letterboxd#3]
When running the module, the following syntax error is thrown:

```
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (F:\Repositories\letterboxd\example.js:1:80)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```

The issue is related to the lack of the expression for the **if** statement on line 51 (index.js).

**Comment by zaccolley** [comment]
cheers for this, gonna add some basic tests at the very least to pick up on this kind of thing in the future (#4)
